---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /containers/heimdall/config:/config
    ports:
      - 8080:8080
      - 443:443
    restart: unless-stopped
---
